language: csharp
solution: TicketBooker.sln

script:
  - xbuild /p:Configuration=Debug TicketBooker.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore TicketBooker.sln
after_script:
  - nunit-console Build/TicketBooker.exe